project_name: Example API Service
project_description: A FastAPI service deployed to Cloud Run
gcp_project: my-gcp-project
gcp_region: us-west2
gcp_service_account: my-service-account@my-gcp-project.iam.gserviceaccount.com
author_name: Example Author
interfaces: api
deploy_targets: cloud-run
