{%- if include_api %}
web: uvicorn {{ project_module }}.main_api:app --host 0.0.0.0 --port $PORT --workers 1 --proxy-headers --forwarded-allow-ips='*'
{%- endif %}
{%- if include_cli %}
# CLI_ARGS is set at execution time by execute_cloud_run_job.sh
job: {{ project_slug }} ${CLI_ARGS:-}
{%- endif %}
